src/lang/TranslationsCS.js

Hi, I've translated the game to czech language.

Added czech translation.

---

src/pages/StreetView.vue

Fix: Position Photosphere

---

package-lock.json
package.json
src/components/History.vue
src/components/widgets/dialog/DialogRoom.vue
src/lang/TranslationsEN.js
src/lang/TranslationsFR.js
src/main.js
src/pages/Home.vue
src/pages/StreetView.vue
src/router.js

Url game : https://xxxxxx/game/____
Url Room : https://xxxxxx/room/____

Url room multiplayer + Url share game

---

src/components/Maps.vue
src/components/widgets/dialog/DialogRoom.vue
src/pages/StreetView.vue

When you start a new game, the map is setup on Bounding Boxes (https://geojson.org/geojson-spec.html#bounding-boxes).

feat(maps): Center on start game

---

src/components/game/DetailsMap.vue
src/lang/TranslationsEN.js
src/lang/TranslationsFR.js

feat: add link to details map

---

src/components/home/SearchBox.vue
src/main.js
src/pages/StreetView.vue
tests/unit/components/home/SearchBox.spec.js

- Fix #67 
- Autocomplete url : https://photon.komoot.io/
- fix #68

Fixs #67 Streetview search radius + #68 Firebase config

---

package-lock.json
package.json
src/components/history/History.vue
src/components/home/Header.vue
src/lang/locale/en.json
src/lang/locale/fr.json
src/mixins/ConfirmExitMixin.js
src/pages/StreetView.vue
tests/unit/components/history/History.spec.js
tests/unit/components/home/Header.spec.js
tests/unit/components/home/__snapshots__/Header.spec.js.snap

feat: #95 confirm exit

---

src/utils.js

fix: #157 country code state

---

src/App.vue
src/store/homeStore.js

fix: #173 StreamerMode not save

---

src/components/history/gameResult/HistoryMapClassic.vue

fix: #213 history distance multiplayer infowindow

---

firebase.json
functions/index.js
functions/package-lock.json
functions/package.json

Fix cloud function clean (node 8 -> node 14)

fix: function clean (node version)

---

src/pages/StreetView.vue

fix: #359 reset button on the floor picker

---

Dockerfile
docker-compose.yml

This pull-request adds Docker support for the application which allows for easier deployments.
You can now `docker build -t geoguess .` to build an image that you can easily use.
Everything is configurable with environment variables, just like on the baremetal install.
Tested by deploying it both locally and then on a production server using the provided example of `docker-compose`.
Signed off by: Jae Lo Presti <me@jae.fi>

Docker: add Dockerfile and docker-compose

---

src/lang/index.js

feat(i18n): Spanish

---

src/pages/StreetView.vue
src/plugins/StreetViewService.js
tests/unit/plugins/StreetViewService.spec.js

fix: end round auto guess

---

.github/workflows/ci.yml
cypress.config.js
cypress.json
firebase.json
tests/e2e/plugins/index.js

chore: cypress 10

---

package-lock.json
src/store/modules/home.store.js
tests/unit/store/modules/home.store.spec.js

fix: openstreetapi search api url

---

package-lock.json
package.json

- [] New feature (non-breaking change that adds functionality)
geoguess require firebase

fix: upgrade firebase

---

src/lang/locale/pl.json

Typo in Polish translation
Locally

Fix PL message for "viewSummary"

---

package-lock.json
package.json

Revert "chore(deps): Bump firebase from 8.10.1 to 12.0.0"
